### ISSUE TITLE
Monsters can't use weapons with ammo requirement

### ISSUE THREAD

**Issue by MMDaemon** [Lee-Talman/knave2e#28]
I have most of my weapons templated so when I have a Bow the default ammo is arrows.

When I give this weapon to a monster and want to attack with it I get the following Error:
`items.mjs:353 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'arrow')
    at hasAmmo (items.mjs:353:50)
    at Knave2eActorSheet.onAttack (items.mjs:238:6)
    at HTMLFormElement.dispatch (jquery.min.js:2:40035)
    at v.handle (jquery.min.js:2:38006)`

I can work around this by removing the ammo requirement from the Item.

Would it be possible to
- either give monsters the capacity to hold items and ammo (could also be used for loot)
- or make it so the ammo reqirement is ignored for monsters.

**Comment by Lee-Talman** [comment]
I will take a look at this for the 0.4.1 release - should be easy enough to just remove the ammo requirement.
